version: "3.9" #version en docker compose
services:
  mysql8:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD= 1428
      - MYSQL_DATABASE= ms_usuarios_db
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - dev-local
  postgres14:
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - dev-local
  ms-usuarios:
  ms-cursos:


volumes:
  data-mysql:
  data-postgres:
networks:
  dev-local: