services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1428
      - MYSQL_DATABASE=ms_usuarios_db
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-local-compose
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - dev-local-compose
  ms-usuarios:
    container_name: ms-usuarios
    image: jesusdevback95/usuarios
#    build:
#      context: ./
#      dockerfile: ./ms-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./ms-usuarios/.env
    networks:
      - dev-local-compose
    restart: always
    depends_on:
      mysql8:
        condition: service_healthy
  ms-cursos:
    container_name: ms-cursos
    image: jesusdevback95/cursos
#    build:
#      context: ./
#      dockerfile: ./ms-cursos/Dockerfile

    ports:
      - "8002:8002"
    env_file:
      - ./ms-cursos/.env
    networks:
      - dev-local-compose
    depends_on:
      - postgres14
      - ms-usuarios
    restart: always


volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
networks:
  dev-local-compose:
    name: dev-local-compose