services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1428
      - MYSQL_DATABASE=ms_usuarios_db
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-local-compose
  ms-usuarios:
    container_name: ms-usuarios
    image: jesusdevback95/usuarios
#    build:
#      context: ./
#      dockerfile: ./ms-usuarios/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: ms_usuarios_db
      DB_USER_NAME: root
      DB_PASSWORD: 1428
      CURSOS_URL: ec2-54-155-148-244.eu-west-1.compute.amazonaws.com:8002
    networks:
      - dev-local-compose
    restart: always
    depends_on:
      mysql8:
        condition: service_healthy
volumes:
  data-mysql:
    name: data-mysql
networks:
  dev-local-compose:
    name: dev-local-compose