apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-api-gateway
  template:
    metadata:
      labels:
        app: ms-api-gateway
    spec:
      containers:
        - name: ms-api-gateway
          image: jesusdevback95/ms-api-gateway:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: ms-api-gateway
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    app: ms-api-gateway