spring:
  security:
    oauth2:
      client:
        registration:
          ms-usuarios-client:
            provider: spring
            client-id: usuarios-client
            client-secret: 1234
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8001/"
            scope: read
            client-name: ms-usuarios-client
        provider:
          spring:
            issuer-uri: http://127.0.0.1:9000
