management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true


spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: ms-cursos
            uri: lb://ms-cursos
            predicates:
              - Path=/api/cursos/**
            filters:
              - StripPrefix=1
              - RewritePath=/cursos(?<segment>/?.*), $\{segment}
          - id: ms-usuarios
            uri: lb://ms-usuarios
            predicates:
              - Path=/api/usuarios/**
            filters:
              - StripPrefix=1
              - RewritePath=/usuarios(?<segment>/?.*), $\{segment}
